# Generated by Django 4.2.21 on 2025-05-20 00:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('keywords_en', models.CharField(max_length=255)),
                ('summary_text_en', models.TextField()),
                ('audio_url_en', models.URLField()),
                ('title_zh', models.CharField(max_length=255)),
                ('description_zh', models.TextField()),
                ('keywords_zh', models.CharField(max_length=255)),
                ('summary_text_zh', models.TextField()),
                ('audio_url_zh', models.URLField()),
                ('gpt_prompt', models.TextField()),
                ('gpt_response_raw', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Daily Digest',
                'verbose_name_plural': 'Daily Digests',
                'ordering': ['-date'],
            },
        ),
    ]
