# Generated by Django 4.2.21 on 2025-05-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0002_rename_gpt_prompt_dailydigest_llm_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydigest',
            name='audio_size_en',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydigest',
            name='audio_size_zh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
